api_key:
  tushare: 'your_tushare_api_key'
  jqdata: 'your_jqdata_api_key'
  xueqiu: 'your_xueqiu_api_key'

stock_list:
  cn_stock:
    include: all
    exclude: ['st', 'st*', 'st*', 'new']
  crypto:
    exchange: okx
    symbol: all
    include_regex: ["USDT"]
    exclude_regex: ["EUR"]
    bar: 
      interval: [1m, 5m, 15m, 30m, 1H, 4H, 12H, 1D, 1W, 1M]
      start: 2019-01-01
      end: now
  
db:
  mongo:
    host: 'localhost'
    port: 27017
    username: 'root'
    password: 'root'
    authSource: 'admin'

gpu:
  use_gpu: False
  gpu_id: 0
  