crypto:
  exchange: okx
  symbol: all
  interval: [1m, 5m, 15m, 30m, 1H, 4H, 12H, 1D, 1W, 1M]
  start: 2019-01-01
  end: now
  
cn_stock:
  exchange: all
  symbol: all
  interval: [1m, 1H, 1D, 1W, 1M, 1Y]
  start: 2010-01-01
  end: now

